[2023-12-02T14:08:18.255+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.crawl_data scheduled__2023-12-02T06:38:16.584995+00:00 [queued]>
[2023-12-02T14:08:18.258+0700] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.crawl_data scheduled__2023-12-02T06:38:16.584995+00:00 [queued]>
[2023-12-02T14:08:18.259+0700] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-02T14:08:18.266+0700] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): crawl_data> on 2023-12-02 06:38:16.584995+00:00
[2023-12-02T14:08:18.269+0700] {standard_task_runner.py:57} INFO - Started process 94638 to run task
[2023-12-02T14:08:18.270+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'crawl_data', 'scheduled__2023-12-02T06:38:16.584995+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpavzf57om']
[2023-12-02T14:08:18.271+0700] {standard_task_runner.py:85} INFO - Job 13: Subtask crawl_data
[2023-12-02T14:08:18.289+0700] {task_command.py:416} INFO - Running <TaskInstance: my_first_dag.crawl_data scheduled__2023-12-02T06:38:16.584995+00:00 [running]> on host phuc-ASUS
[2023-12-02T14:08:18.321+0700] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MY_NAME' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='crawl_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T06:38:16.584995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T06:38:16.584995+00:00'
[2023-12-02T14:08:18.322+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T14:08:18.322+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'scrapy crawl quotes']
[2023-12-02T14:08:18.327+0700] {subprocess.py:86} INFO - Output:
[2023-12-02T14:08:18.592+0700] {subprocess.py:93} INFO - Scrapy 2.11.0 - no active project
[2023-12-02T14:08:18.592+0700] {subprocess.py:93} INFO - 
[2023-12-02T14:08:18.592+0700] {subprocess.py:93} INFO - Unknown command: crawl
[2023-12-02T14:08:18.592+0700] {subprocess.py:93} INFO - 
[2023-12-02T14:08:18.592+0700] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2023-12-02T14:08:18.664+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-02T14:08:18.669+0700] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/phuc/Practice/DataScience/DSProject/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-02T14:08:18.671+0700] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=crawl_data, execution_date=20231202T063816, start_date=20231202T070818, end_date=20231202T070818
[2023-12-02T14:08:18.683+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task crawl_data (Bash command failed. The command returned a non-zero exit code 2.; 94638)
[2023-12-02T14:08:18.723+0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T14:08:18.733+0700] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
